import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/sidebar";
import NavBar from "@/components/navbar";
import { ProjectProvider } from "@/context/ProjectContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased dark`}
    >
      <body className="bg-[#1e1e1e]">
        <ProjectProvider>
          <NavBar />
          <div className="flex h-[calc(100vh-58px)] bg-[#1e1e1e] overflow-hidden">
            <SideBar />
            <main className="flex-1 h-full overflow-y-auto">{children}</main>
          </div>
        </ProjectProvider>
      </body>
    </html>
  );
}